kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: echo-api
  version: 1.1.0
  namespace: test001
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./echo-api-spec.yml
  cors:
    $ref: test001:cors-echo-api:1.1.0
  policy-sequence:
    - $ref: test001:assembly-echo-api:1.1.0
