kind: CORS
apiVersion: api.ibm.com/v1
metadata:
  name: cors-echo-api
  namespace: t01
  version: 1.1.0
  tags: []
spec:
  rules:
    - action: allow
      originList:
        - '*'
      allowCredentials: false
      exposeHeaders:
        predefined: false
        custom: ''
        backend: false
